[package]
name = "u02"
version = "0.1.0"
authors = ["fin"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.23"
num = "0.4.0"
rand = "0.8.5"
